allowBuilds:
  electron: true
  electron-winstaller: true
  bufferutil: false
  ip-set: false
  node-datachannel: true
  utf-8-validate: false
  utp-native: false
patchedDependencies:
  bittorrent-tracker@11.2.3: patches/bittorrent-tracker@11.2.3.patch
overrides:
  "bittorrent-tracker@11.2.3>ip": "-"
